#!/usr/bin/env bash

# Record my screen. It might only work my computer because
# I had to change some parts for it work on the MacBook.
#
# Not completly sure if this is correct, but if you want this to
# to work on your PC, replace "-i :1" with "-i :0.0"

FNAME="$HOME/Videos/screencast-$(date '+%y%m%d-%h%m-%s').mp4"

record_selection(){
    # Select the area using hacksaw. We are using the -n flag
    # to remove the extra lines hacksaw show normally
    geometry=$(hacksaw -n)
    x=$(echo $geometry | grep -o -E '[0-9]+' | tail -2 | head -1)
    y=$(echo $geometry | grep -o -E '[0-9]+' | tail -1)
    width=$(echo $geometry | grep -o -E '[0-9]+' | head -1)
    height=$(echo $geometry | grep -o -E '[0-9]+' | head -2 | tail -1)
    ffmpeg -y -f x11grab -framerate 60 -s ${width}x${height} -i :1+${x},${y} -f alsa -i default -r 30 -strict -2 -c:v libx264rgb -c:a flac $FNAME

}

record_full_screen(){
    ffmpeg -y -f x11grab -framerate 60 -s $(xdpyinfo | grep dimensions | awk '{print $2;}') -i :1 -f alsa -i default -r 30 -strict -2 -c:v libx264rgb -c:a flac $FNAME

}

# WARNING: dont use this function, it needs to be fixed.
# Use selection option and just drag and trace the window for now
record_window(){
    # This does not work properly yet.
    # The coordinates are a little off when given to ffmpeg
    geometry=$(xwininfo | grep -- "-geometry")
    x=$(echo $geometry | grep -o -E '[0-9]+' | tail -2 | head -1)
    y=$(echo $geometry | grep -o -E '[0-9]+' | tail -1)
    #y=expr $y - 20
    echo "x y"
    echo $x $y
    width=$(echo $geometry | grep -o -E '[0-9]+' | head -1)
    height=$(echo $geometry | grep -o -E '[0-9]+' | head -2 | tail -1)
    echo "w h"
    echo $width $height
    ffmpeg -y -f x11grab -framerate 60 -s ${width}x${height} -i :1+${x},${y} -f alsa -i default -r 30 -strict -2 -c:v libx264rgb -c:a flac $FNAME
}

# Parse the arguments
options=$(getopt -o h --long f:,s,help -- "$@")
eval set -- "$options"

while true; do
    case "$1" in
        -s)
            record_selection
            exit
            ;;
        -f)
            shift
            FNAME="$HOME/Videos/$1"
            ;;
        *)
            record_full_screen
            break
            ;;
    esac
    shift
done

