#!/usr/bin/env bash

# Record my screen. It might only work my computer because
# I had to change some parts for it work on the MacBook.
#
# Not completly sure if this is correct, but if you want this to
# to work on your PC, replace "-i :1" with "-i 0:0"

ffmpeg -y -f x11grab -framerate 60 -s $(xdpyinfo | grep dimensions | awk '{print $2;}') -i :1 -f alsa -i default -r 30 -strict -2 -c:v libx264rgb -c:a flac "$HOME/Videos/screencast-$(date '+%y%m%d-%H%M-%S').mp4"




