#!/usr/bin/env python3

import sys

with open("/etc/hosts", "r") as f:
    lines = f.readlines()
try:
    d = lines.index("###BLOCKED WHILE STUDYING###\n")
except ValueError:
    print("You havent blocked any sites for studying!")
    sys.exit()

final = lines[:d]

f.close()

with open("/etc/hosts", "w") as f:
    for thing in final:
        f.write(thing)

f.close()

print("Removed blocked sites :)")
