#!/usr/bin/env bash
VIDPATH="$HOME/videos/recordings/rec_$(date '+%y%m%d_%H%M_%S').mkv"
PIDPATH="$HOME/bin/utils/recorder/recordingpid"

video() {
    echo "Recording started"
    ffmpeg \
    -hide_banner \
    -loglevel panic \
	-f x11grab \
	-s $(xdpyinfo | grep dimensions | awk '{print $2;}') \
	-i $DISPLAY \
 	-c:v libx264 -qp 0 -r 30 \
	"$VIDPATH" &
	echo $! > "$PIDPATH"
}

screencast() {
    echo "Recording started"
	ffmpeg -y \
    -hide_banner \
    -loglevel panic \
	-f x11grab \
	-framerate 60 \
	-s $(xdpyinfo | grep dimensions | awk '{print $2;}') \
	-i $DISPLAY \
	-f alsa -i default \
	-r 30 \
 	-c:v libx264rgb -crf 0 -preset ultrafast -c:a flac \
	"$VIDPATH" &
	echo $! > "$PIDPATH"
}

end_recording(){
    kill -9 $(cat "$PIDPATH")
    echo "Recording ended"

}

case "$1" in
	screencast) screencast;;
	video) video;;
    end) end_recording;;
	*) echo "No argument was given";;
esac
