#!/usr/bin/env bash
#
# by Siddharth Dushantha 2020
#

DMG="$1"

# /path/to/MyApp.dmg --> MyApp.dmg
filename_w_ext=$(basename -- "$DMG")

# MyApp.dmg --> MyApp
filename="${filename_w_ext%.*}"

# Extract file contents from DMG
7z x "$DMG" -y >/dev/null

# Change directory into the directory which just got extracted
cd "$filename" || exit

# Get the app identifier
command ls -d -- *.app/ | sed 's#/##'

cd -- *.app/Contents || exit

# Get the bundle identifier
grep -A 1 "CFBundleIdentifier" Info.plist |\
    tail -1 |\
    sed -e 's/\s*<string>\(.*\)<\/string>/\1/'

# Go back to intial working directory
cd ../../../

# Remove the extracted content
rm -rf "$filename"

