#!/usr/bin/env bash
#
# Quick script to take notes
#

NOTES_DIR="$HOME/documents/notes"

[ $# -eq 0 ] && exit 

if [ "$1" == "ls" ]; then
    ls "$NOTES_DIR" && exit
else
    cd "$NOTES_DIR"  && nvim -c ":Goyo | set nocursorline | set noshowmode | set noshowcmd | set shortmess+=F" "$1" && exit
fi


